### ISSUE TITLE
Step 5 last bullet

### ISSUE THREAD

**Issue by girishadobe** [adobe/aem-forms-af-runtime#6]
We are trying to re deploy the AEM  code with the changes as part of the last bullet in step 5(mvn -PautoInstallPackage clean install)
The complete log is attache
[aem-redploy.txt](https://github.com/adobe/aem-forms-af-runtime/files/9303495/aem-redploy.txt)
d

**Comment by iamsudhanshu** [comment]
Hi Girish.

Could you help verify:
- NPM is available on your system: `npm -v`
- GIT is installed on your system: `git -v` (NPM requires GIT to access packages which are available on public GitHub repository - in our case - https://github.com/adobe/json-formula).
- On windows - you are running the command using _Run as Administrator_ option.

**Comment by girishadobe** [comment]
the error went away!!!!. I  am good now

**Comment by girishadobe** [comment]
Yes- the previous steps worked fine
Only at the last step it is failing

Sent from my iPhone

On Aug 11, 2022, at 5:35 PM, Sudhanshu ***@***.***> wrote:

﻿

EXTERNAL: Use caution when clicking on links or opening attachments.


Hi Girish.

Could you help verify:

  *   NPM is available on your system: npm -v
  *   GIT is installed on your system: git -v (NPM requires GIT to access packages which are available on public GitHub repository - in our case - https://github.com/adobe/json-formula<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fadobe%2Fjson-formula&data=05%7C01%7Cgbedekar%40adobe.com%7Cfa2e4f38404d4fdeee2308da7bfa93af%7Cfa7b1b5a7b34438794aed2c178decee1%7C0%7C0%7C637958613396572262%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=zasaN3M70TXyv4Rs7ywW%2BEvtkD58hgi6Gk0%2F%2BDu8CIk%3D&reserved=0>).
  *   On windows - you are running the command using Run as Administrator option.
